id: A4DF8D680
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
type: translation
pechas:
- I0B9FA0AF
- I296AF6DF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:19.175280
  last_modified_at: 2023-01-04 11:55:19.175292
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I0B9FA0AF/9388: F282
  I296AF6DF/F755: F282
